apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamcity-default-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - teamcity.cluster.ldtteam.com
      secretName: teamcity-default-tls
  rules:
    - host: teamcity.cluster.ldtteam.com
      http:
        paths:
          - path: '/'
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  name: http
