---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8111
      targetPort: http
  selector:
    app: {{ $.Release.Name }}
    component: server
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
    - name: http
      protocol: TCP
      port: 8111
      targetPort: http
  selector:
    app: {{ $.Release.Name }}
    component: server

{{range $index, $e := until ($.Values.replicas | int)}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $index }}
  annotations:
    node-id: {{ $.Release.Name }}-{{ $index }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8111
      targetPort: http
  selector:
    app: {{ $.Release.Name }}
    component: server
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-{{ $index }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-direct-h{{ $index }}
  annotations:
    node-id: {{ $.Release.Name }}-{{ $index }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      protocol: TCP
      port: 8111
      targetPort: http
  selector:
    app: {{ $.Release.Name }}
    component: server
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-{{ $index }}
  type: ClusterIP
{{- end }}
