---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-credentials
  namespace: external-dns
spec:
  encryptedData:
    api-key: AgDBvpHsxXnjhY0D9OvDYQ9TR1POVOunZr1BXapxYG/7XKhJS61Xfyi55Jf0futZdw9MlplpIQ7aNuDW7fZa+3KHI85VxVpcvGGpkZyLE4jsiVj6MBzouxoiP5/+BSa13ePbumJuAVqWxJWI1vjYfIOJRLq19lUTEgxoMKUK3F4sPpKrFjW0xy4d4dbmDhTLfYNQ+qGiHf14U3u/mQ+tLLOWwmIQEmQ3YVqalqLn+j/SBnAM9V0VMGjjK6GA6Yf5MPSF/qfLlnV2wCOgC0M4W9IJyfBh2NiMvoUp+5c6RcpC5iSjI78MQ+xQ06yIwU79+tk7NOWJOXmOVtPATAm0yZqtiMon65OD25f4i0eqVJGobFYwHVI9TTv4nDRZWp+lwRHiR4OfVPDq6q5ak/H5rJjOEWIuQzIGlpZpyTq+nzH7XQRUnh3c4AII7ad0VkbKyKf8CDhO7VOH3iy9qXNK2fMmosXl+xvkO52uiw7r4myRk+n1VXhE4U9Fl2mgiVchjoo+djTk/NYYq6DUlJoDdgoxqBQnRB1LG3viuGL2RZbbsL1bvcsr2+UR38mKPfTvUyr6W/TcHsusU19I2yCUbFNGa+X2xRl+qasvc1dKWFfetMyqLHNtTyUefFlAFtDb8SyXPgNMc0058u58JY4KPGHi65n4x/+w1wB6aZ0dQG9I9L/zSQEvJlHpKbHYFZlG4+tmCmsFrZphNxupiaa1n9KWlcaw+NNKzetQo5U3deIVj7+CAgk8azlmq2k/bn96DDw7hWVgZfC3rksw9mDMJ8Bk
  template:
    metadata:
      name: hetzner-credentials
      namespace: external-dns
      labels:
        app.kubernetes.io/part-of: external-dns
