---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-credentials
  namespace: external-dns
spec:
  encryptedData:
    api-key: AgACmzgCSwi5LJjsiFTxX8UZje9e7KnR21n/HbDZiayvzyj12DplWZ3YpC9G5jHzsOCMQms/WVg0DXUjLS2Dzf7lAFAdmTTddBx+NNzNu4qseeRTC9n2Lx6y57LepNEUs5Hm2vzZSgsXHHYvauywnMxddGs/fBYJ6O2HotTakVp55vF/sGC8UwOLmzViLnev2qSjyvLjFboE181GsEmN71RRWDc4XAwtjc4VszSD+tKkBCAo1TypOUay5bWl0wDa0r0PUhbxigJqrt7cdxpT6YlcG5ykHVf+eXzTRDLupsWXsnt4meg9m2hD6/E2Ot4zVAlrvwy+/y0WQDROBJZ0nlKbTsG5wc8VwE5KLyrn7nMm+grpCw5+Akcm5D6yStyjOLTYTZG6hIJAJlo5fokiQ8UbxhsOaHlZqpXHimI56TWMjcOK2tbwzvIftOtNEilPXTQKgteie4k/PtU2RIk/lDt01EJuTLNlRx3R88XDcgCv7AuHfzoEGcynRz5gF2ie935NNfuU7XmRJg4C7YK35jzm9zTMQe8G4zuOT12wDhslYQ1ag7ueLn7aR9BWXb0M6+HiP4y96QPHnxVfNrRMKUr4BvMPWrjVj656iueqhVUidDhqUrOAfHfRGKDXjpNzciPi5nZ7x7x/uvqkFZ46GHxNTqdyYF0pLqRI8xcq9G8AisbY4B11fUIe4YQGb4lR9nf0oARN5VXWGovKzCSRd7/Ih0ahSQ42bZF72XHAadrmgw==
  template:
    metadata:
      name: hetzner-credentials
      namespace: external-dns
      labels:
        app.kubernetes.io/part-of: external-dns
