---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-credentials
  namespace: external-dns
spec:
  encryptedData:
    api-key: AgC3/THO2zJo4CAz33QVDBi3dXF4sc0NKYGDh2GeBxBzGO4KlwQKVGTdzzIJqlJzdH3XZSDEzOrfldb/JSjgc7h5tk9ILJDAchFuAxDcj4TYlKk2Ax1Xj945lSVdUtSA2Z3n8PDlhatp6GpFyu7UgFv+uH7EhcaVz3+69l6yYAIjHvIbYoBCLuu6EY/M96xZWz4bvG223cB+j/UCXeIYEBgn45k5o9nQtKLSkeLqDiTEfboW2tUKdlUtlYvTbIPrOoA4lVgGi+JncQ/Opf2Yg/s/YTBce63h2Xk/VV3DPkmBY+Fub0szFF5GzDaEGc9K3zcaWpRxlrvrjCwsSXN8KBvnOFxBzXMQPGX5SKy72E0LWQJIRruhnmE9KYXkgwPPCZcHz1GbborIyiL88Ta4/Cadoje881JHHeVVQNazxY84d9TDsEQLzwoeRTJic4yJAvRjHr3E5O5E61ba4cw+Ch+Jdgn6SqrOAghpS2yu15s1ggsP1wV4+afFc+8RmBEhnEsmcW7gv9ZeM6cr55s5m15skqfdXTtQbjCYgBvHcDYA2RTwMqJztYxx1eFqIoUOhNbDkli0YV74VrHMXMjsO0tr3fmiEiV4a+HRJB7Qfp+9VuMgcBYyQRjW6p3OXRMjrszZfjTtHSEZ2U3XMvUHQO+3UMGdP+Hg4ifR0g9MQpkGY4T3+V7GnBhdAiq1cdtdUuq5FNUxRcL41+a0roYz/OjSI8N+TfoMh+Jawnv+QjJOkw==
  template:
    metadata:
      name: hetzner-credentials
      namespace: external-dns
      labels:
        app.kubernetes.io/part-of: external-dns
