---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: parchmentmc-cloudflare-api-token-secret
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgDBPRkdKSxtxZ2GVIXaUcU9Tk21PUTYSXeBi/p3YfRcW1xtSzBpFMcvZjx4qx2wd4BqzAAYTc3Q3/mnDm3KjNFSD3N3oq7eXHLw8Nm1gwP7A2Jn7XIgMh01tArT3R7wD3SqbC3FzXn+pwIlwM1kOBvF79befFgSKJ7QRPsD2hFsqgivNG6nWCfkLu08PaK/xw+y6vWS0ie41Al2xtDpzCxETFr7qq+SBP64DhF3rFb315Lrh9d+tzw8YGSNiTsWaA+BGCRPJrHqZqlJNH0m36bOVLFSacKRMM61WI0OOOpoXVWR92razfiwHx91uWLnz2fGovEtJYmQZ3Xti4lmXLfgOedYVMV4mJFWRR8SMHCjgpiIbkicaAH7xAsqdnQabgdWGbDbBvOm33OPakjZdxVwZG7mP/1mvV2CARvNeOtBNeQpYkEn5s+RIf9MuS36hlTXoTUzHB/oggnkoA4elKiFbbJBOqDdxIEV4nRvil47RRqE7h+mhpNAJ2E/CzTWrkB2kNOI47Ny4JrSGIxExloX9qcB/cKNal7k5+/rJ2qAO4e8ufbujs+m3+nYdFxf9mkioStyY2uPno4LP/55uRzAqtM7BsIMiAAaMLSy6abPiBMDklcpghBOHyVDjJlRcNVzKyDGWPspzhXZf8d1PQZ5hr5Cp+kakEllUsN8JdTIFHUA70WCD/YmPzZPCR17zkn0aQH8fVBeNb9UeYnPkj9EAsUcmlkOIOm6T+2AfBUb2flW82E8Ihmu
  template:
    metadata:
      name: parchmentmc-cloudflare-api-token-secret
      namespace: external-dns
      labels:
        app.kubernetes.io/part-of: external-dns
