---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: maven-operator-system
spec:
  encryptedData:
    .dockerconfigjson: AgBy/7zsCVW10peN0cZ9KIv/HZbE0WGDcIohl4DlesE4eKEXoR2MfBjKehIt1anFqpUF1vif++jF5UredQd+/Pf5w8A3JZJkqhLyIwG8V/+hqgCSpzxdK+dhlSTkXJEtypVtrGx1jLDHzyKaTMthp/NiJZdLVyjAieHs0sB/OIyPuCq6h22b/1xai9LL4rSpZjVHnGJNKgh054/j+1YZkh1YhsPlyHggbKIACTZsWBxAJntI6jSBQTRSEdQ0G2gyl3xLal8RJrJgWr2PiiJ3Dhygv452B1S7AOFD/2RdPUUg2BRo/dddnd7ZJX/5kOeTKaLOGI+7O4OD5UtCwFkV/pLiSc3I7vMqNc4tissVlSfNp5mpg2iCXN1oMehZJhs4Ix5/L9oZdVyHCjUx2akEmvyImz4Kuo+dT/6S/pwetS23TjTemg3RyNJt607KAjjl2DfcTM21NyV4gPo0KT7jtwzty+bqiOifLtMNGrMF1deJb4MB5X0xhE3JH5OG6IkXbyc7F6d/0wE43rQRNPk1KYJtfi5ZNMuLiGAPOUXNPSS4PgD+TR8VAl8E4KYh1D8EXxz3xWPD+F65WBa/0eCY9d7B1lUf+ma0j0ZJt0ALnFBSiNUaUAQ48J9zSHRn298klnmdEBoI3J6bMVZXZEcw3gbJZPlKcn0EnXqYepW4pH4s7O0XrIxyAlN1BzcMqGGBnDTMXoiImUQFTe2Ly72rEVwNKrw7537aUkxJ1zu2+l8msaubz0IKP99KpXh9ELJNHAV0VhR7Vtrzoi52/Z6dHLxvfgr8L7iT/o9EJyyyNdpR9qSDKhAKhDu26YmGLstvwJzjR3cv+j4xoV8bDE/6dY5tsfxw8XTVBAisBwdJeBimkifMYkNGgiHAkmR2MZHOrYZb0RQ6NrZhsgnvIrdCcLcHNZ78yJoaVZgpv/88gBaYlSxyYDKqVh9Q
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: maven-operator-system
      labels:
        app.kubernetes.io/part-of: maven-operator
    type: kubernetes.io/dockerconfigjson
