apiVersion: v1
kind: Secret
metadata:
  name: backblaze-backup
  namespace: longhorn-system
  labels:
    app.kubernetes.io/part-of: longhorn
type: Opaque
data:
  AWS_ENDPOINTS: aHR0cHM6Ly9zMy51cy13ZXN0LTAwMi5iYWNrYmxhemViMi5jb20K
