apiVersion: v1
kind: Secret
metadata:
  name: backblaze-backup
  namespace: longhorn-system
  labels:
    app.kubernetes.io/part-of: longhorn
type: Opaque
data:
  AWS_ENDPOINTS: https://s3.us-west-002.backblazeb2.com
