---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-backup
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA5tB97rj8oT+Abq7UAycitkaPyg0IqOp/LeyCxnRv/ElJJrsaisStbj0V7W13/AwyZ2N/x5KiitppXWyMWzxGhBgg0+ZEfWlpd1h+CXMAgybf6UJv6v/YokTn1oJFQXDSz+3TvARVUNaZ6+3t94otWuD4Eyi2b2f2fWOsJklm+meq/y77zNj3Yqh7qIUf/mxP4Wzjdo74YDkg9VOAfJiFb7txB653EJSVvt4CnlLQfIsQnlT2jGqZFHLYGas9YOC4ydXi1WHB1WjRBJwYb+W1V0Aacfd4eM3U2k6oZFL5s4jPDqqJU3csrqg7eVkvVVnMx8JLkZxJ1tKxK5qVRfherfAyxaa66iel/6PaHTM6O3YZ4odYkjKtBF5ilMF8qWHOmxQDPwaNrasmdvayWnvI93DbAvCNlC3AHSTmeftv0ux+unjtV+0DGm4Lm7s+IHkzXGm1RCsoDMl9YLpAa4rdhp2SShqoXtSGFNyfdmyc71x2f+fqFgtdN+9fsXdVrD/wGVv2BqlQm76274DpbRAw99D9IUSKd73MxJuHPQrpdA2+O1WB8ZvZe6kcOFfv1tKDbGesFDppqYBNZmnIaNSnhubrpG5zJpmA6qGe0X8gA5RXZxqmrITKHznEEsigagaUbd5EPV1fHS9tx45gM5aYHpjSIjSMzhzlJnM6UUhncTQuFMtdjABwr0QF1OQDStwFWUNrliKeHjCAs0R3PayGWgvSCop4E/hqK
    AWS_SECRET_ACCESS_KEY: AgCC0735naoRIHkzCDrXNlngDl/N9t8JQxCLYAme9uuOlVrPfVpXCBiVv4559SwDTUw4HhwoG4w4Nx03oxMFfjiBM4SuzwS0wuHB6UJJIcS6oALvS8DG/HUQJ7zFa4SemUufJsjC5/mxcKnLLJL6XbVgy/GvBDHFtgtAaqe62WKoXoX6f9dQ96yiSN2xNixXWWftv/K5zCRKNNF6npZ1fDpmLkrVOVU4rKx9idHeil7GEgYc4Hw3ycUgmI7JPHprwwslXdS8Sf+ywlYcgeMZuHmzNp5LLafZSM/8OSW+N6UmcuJbTX3ZrW+cEEIs/HSKfdKRq7F8QWotC6QFw2e5Xn9NeFWkpnN9Xfkho6Kq0ZdUgq1ds+nFci3JTrNrJhs/2tWdkSvWwLYrPOjFd5mJRRtcSFxKh2yQ9a0XqrOAcxvg3XoTnNKUMgdTsCKGbkl9ZCSZoYCLDD9R5WrvBoY/JJiFMRcDuxgVDVnPFD5bXJU7SVV1FfSPRa52Z54iSqH+BrwvVgdMEnTikoo2bfaG4snbl9QxT747No/rLr+uy8CvCTivc5eE4Ve91OEE2uOsWM2czd/UDRXc4Ar8WTUcwO4GPatPpVxPbu6G7424U+1chSM0WsKvN45iDfyvPG70kXg8UX2dGqOXl/dlpnZwUPFPJVIP/JUAZr4aAqSBVrDb0UVVi5nEJYzlElu23FMH+2DkTuW9YO51Pd+JEeofE5dBBVJFkAHDqrGofIWnsoxl
  template:
    metadata:
      name: backblaze-backup
      namespace: longhorn-system
      labels:
        app.kubernetes.io/part-of: longhorn
