replicaCount: 1

global:
  storageClass: "longhorn"

image:
  repository: jetbrains/teamcity-server
  tag: 2022.10.3
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

service:
  type: ClusterIP
  port: 8111

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: teamcity.cluster.ldtteam.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: teamcity-ingress-tls
      hosts:
        - teamcity.cluster.ldtteam.com

resources:
  requests:
    memory: 4Gi

postgresql-ha:
  postgresql:
    username: teamcity
    password: teamcity
    database: teamcity

persistentVolumeClaim:
  name: teamcity-server-data
  annotations:
    helm.sh/resource-policy: keep
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
