apiVersion: v1
kind: Endpoints
metadata:
  name: mikrotik-backplane
  namespace: {{ .Release.Namespace }}
subsets:
  - addresses:
      - ip: 149.88.43.166
    ports:
      - port: 8080
        protocol: TCP
        name: HTTP
      - port: 8443
        protocol: TCP
        name: HTTPS
