apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mikrotik-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com"
spec:
  rules:
    - host: andromeda.firewall.ldtteam.com
      http:
        paths:
          - path: /.well-known/acme-challenge
            pathType: Prefix
            backend:
              service:
                name: mikrotik-backplane
                port:
                  number: 80