---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: github-oauth
  namespace: argocd
spec:
  encryptedData:
    client-secret: AgA4tYmSylyN4kx2VwUdJPZQf3GDmPrxoYpTWQXbLiUpoi1WMDMSNq17i8JdNLMwKChZ+30LY+/UtL3nJRd6HVZNX2O6+Qqmq/zbSDxx8oEuB0Kqievsu3Fe3msUE/mr42Hw5gpUHwPTuIth2oCLKTSPsAKqfZtDjd+T+MX9guSwvn2BjVxwPmE8i+IAwzgo9d3hx+XBKtAkIcVb8z/VJ2C2mVdx1/eshfPSkKTvJb6tYo93JW0IIjcJ1diJ8jGqnDX/cIfuka3NF4ueM71TUiu9f+XLTmAskfR4o2xihuoQ63mi8/NmsRoIRFF+dV6IDXce7hArY8Rf6COBuFZQMNgB55CUbLtyF82wSmaFiqKvmXEpOXGPlpsUqJQUy8gJsyGoBxNdNhHcRC5Hs+6R8mRYeNd342oZ+Ay9+rfnP2P4v7IDxTcD4woA4SIQKCheEVsASVWFFVXLp7czJ4fG8qxpIL5GtvcKZaM+XcAfgQPjxgGi8j7ZaeQ0/awjUQX2NTqo7/9bRCljwHsZdlc0NztWDVmqYkcT9G0vp3NMpqq2p1RyZ5zZcuPiUvapauq1qFSTiqpayv0113UDwFyLCYNmXhzNCqvDj3HR4nPjY7QPIVpI7WdUbH0vRvXeKBa2qK9d8Hg9IAe8YfbzEeSyxS+zyhE2Eaq2sl54Zh1oQ8JeFd+rbYlAWVy6Ty8VMfa+uiB2ICmrQ8XLIIg3xjwUxN0A0pI64iakDlHJST8VPM7TSrMb6nXgP9HZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: github-oauth
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
