apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skulleu-teamcity
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: skulleu-teamcity
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: http://charts.sandermann.cloud
      chart: teamspeak3
      targetRevision: 1.0.0
      helm:
        values: |-
          persistence:
            enabled: true
          service:
            annotations:
                metallb.universe.tf/loadBalancerIPs: 192.168.254.0
