apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.7.1
      helm:
        valuesObject:
          configs:
            params:
              server.insecure: true
            cm:
              url: https://argo.cluster.ldtteam.com
              application.instanceLabelKey: argocd.argoproj.io/instance
              admin.enabled: true
              exec.enabled: true
              dex.config: |
                connectors:
                  # GitHub example
                  - type: github
                    id: github
                    name: GitHub
                    config:
                      clientID: Ov23lipfXF8e0zgVR5i6
                      clientSecret: $github-oauth:dex.github.clientSecret
                      orgs:
                      - name: ldtteam
                      - name: parchmentmc
            rbac:
              policy.csv: |
                g, ldtteam:cluster-admins, role:admin
                g, parchmentmc:toolchain, role:admin
          redis-ha:
            enabled: true
          controller:
            replicas: 1
          server:
            replicas: 3
          repoServer:
            replicas: 3
          applicationSet:
            replicaCount: 3
    - repoURL: {{ .Values.repository.url }}
      path: core-charts/argocd-extras
      targetRevision: HEAD
      helm:
        parameters:
          - name: domainName
            value: argo.cluster.ldtteam.com