apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.7.1
      helm:
        valuesObject:
          configs:
            params:
              server.insecure: true
            cm:
              url: https://argo.cluster.ldtteam.com
              application.instanceLabelKey: argocd.argoproj.io/instance
              admin.enabled: false
              exec.enabled: true
              dex.config: |
                connectors:
                  # GitHub example
                  - type: github
                    id: github
                    name: GitHub
                    config:
                      clientID: Ov23lipfXF8e0zgVR5i6
                      clientSecret: $github-oauth:client-secret
                      orgs:
                      - name: ldtteam
                      - name: ParchmentMC
                      - name: ChiselsAndBits
            rbac:
              policy.csv: |
                p, marc.hermans@ldtteam.com, projects, create, *, allow
                p, marc.hermans@ldtteam.com, projects, *, hermans, allow
                p, marc.hermans@ldtteam.com, applications, *, hermans/*, allow
                p, marc.hermans@ldtteam.com, logs, *, hermans/*, allow
                p, marc.hermans@ldtteam.com, exec, *, hermans/*, allow
                p, marc.hermans@ldtteam.com, projects, *, default, allow
                p, marc.hermans@ldtteam.com, applications, *, default/*, allow
                p, marc.hermans@ldtteam.com, logs, *, default/*, allow
                p, marc.hermans@ldtteam.com, exec, *, default/*, allow
                p, marc.hermans@ldtteam.com, repositories, *, *, allow
                p, marc.hermans@ldtteam.com, extensions, *, *, allow
                p, marc.hermans@ldtteam.com, clusters, *, *, allow
                p, ldtteam:Cluster Admins, projects, create, *, allow
                p, ldtteam:Cluster Admins, projects, *, ldtteam, allow
                p, ldtteam:Cluster Admins, applications, *, ldtteam/*, allow
                p, ldtteam:Cluster Admins, logs, *, ldtteam/*, allow
                p, ldtteam:Cluster Admins, exec, *, ldtteam/*, allow
                p, ldtteam:Cluster Admins, projects, *, default, allow
                p, ldtteam:Cluster Admins, applications, *, default/*, allow
                p, ldtteam:Cluster Admins, logs, *, default/*, allow
                p, ldtteam:Cluster Admins, exec, *, default/*, allow
                p, ldtteam:Cluster Admins, repositories, *, *, allow
                p, ldtteam:Cluster Admins, extensions, *, *, allow
                p, ldtteam:Cluster Admins, clusters, *, *, allow
                p, ChiselsAndBits:Cluster Admin, projects, *, chiselsandbits, allow
                p, ChiselsAndBits:Cluster Admin, applications, *, chiselsandbits/*, allow
                p, ChiselsAndBits:Cluster Admin, logs, *, chiselsandbits/*, allow
                p, ChiselsAndBits:Cluster Admin, exec, *, chiselsandbits/*, allow
                p, ChiselsAndBits:Cluster Admin, projects, *, default, allow
                p, ChiselsAndBits:Cluster Admin, applications, *, default/*, allow
                p, ChiselsAndBits:Cluster Admin, logs, *, default/*, allow
                p, ChiselsAndBits:Cluster Admin, exec, *, default/*, allow
                p, ChiselsAndBits:Cluster Admin, repositories, *, *, allow
                p, ChiselsAndBits:Cluster Admin, extensions, *, *, allow
                p, ChiselsAndBits:Cluster Admin, clusters, *, *, allow
                p, ParchmentMC:Toolchain, projects, *, parchment, allow
                p, ParchmentMC:Toolchain, applications, *, parchment/*, allow
                p, ParchmentMC:Toolchain, logs, *, parchment/*, allow
                p, ParchmentMC:Toolchain, exec, *, parchment/*, allow
                p, ParchmentMC:Toolchain, projects, *, default, allow
                p, ParchmentMC:Toolchain, applications, *, default/*, allow
                p, ParchmentMC:Toolchain, logs, *, default/*, allow
                p, ParchmentMC:Toolchain, exec, *, default/*, allow
                p, ParchmentMC:Toolchain, repositories, *, *, allow
                p, ParchmentMC:Toolchain, extensions, *, *, allow
                p, ParchmentMC:Toolchain, clusters, *, *, allow
                g, ldtteam:Cluster Admins, role:read
                g, ParchmentMC:Toolchain, role:read
                g, ChiselsAndBits:Cluster Admin, role:read
          redis-ha:
            enabled: true
          controller:
            replicas: 1
          server:
            replicas: 3
          repoServer:
            replicas: 3
          applicationSet:
            replicaCount: 3
    - repoURL: {{ .Values.repository.url }}
      path: core-charts/argocd-extras
      targetRevision: HEAD
      helm:
        parameters:
          - name: domainName
            value: argo.cluster.ldtteam.com