apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.11.0
      helm:
        parameters:
          - name: installCRDs
            value: "true"
    - repoURL: {{ .Values.repository.url }}
      path: charts/cert-manager-extras
      targetRevision: HEAD