apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.16.1
      helm:
        parameters:
          - name: installCRDs
            value: "true"
        valuesObject:
          enableCertificateOwnerRef: true
          dns01RecursiveNameservers: 8.8.8.8:53,1.1.1.1:53
          dns01RecursiveNameserversOnly: true
          
    - repoURL: {{ .Values.repository.url }}
      path: core-charts/cert-manager-extras
      targetRevision: HEAD
      
    - repoURL: https://charts.hetzner.cloud
      chart: cert-manager-webhook-hetzner
      targetRevision: "0."
      helm:
        releaseName: cert-manager-webhook-hetzner
        valuesObject:
          groupName: acme.ldtteam.com
