apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.7.0
      chart: ingress-nginx
      helm:
        valuesObject:
          controller:
            resources:
              requests:
                cpu: 400m
                memory: 350Mi
            autoscaling:
              enabled: true
              minReplicas: 3
              maxReplicas: 4
            minAvailable: 2
            updateStrategy:
              rollingUpdate:
                maxUnavailable: 1
              type: RollingUpdate
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: ingress-nginx
                        app.kubernetes.io/component: controller
                        # This should be the same as the release name
                        app.kubernetes.io/instance: ingress
                    topologyKey: "topology.kubernetes.io/zone"
            nodeSelector:
              ldtteam.com/ingress: "true"
            service:
              annotations:
                metallb.universe.tf/loadBalancerIPs: 192.168.254.1
            metrics:
              enabled: true
              serviceMonitor:
                  enabled: true
                  additionalLabels:
                    release: prometheus
