apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ldtteam
  namespace: argocd
spec:
  project: ldtteam
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ldtteam
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https:://github.com/ldtteam/LSAT
      path: ldtteam-services
      targetRevision: HEAD
      helm:
        values: |-
          repository:
            url : https:://github.com/ldtteam/LSAT
