apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parchment
  namespace: argocd
spec:
  project: parchment
  destination:
    server: "https://kubernetes.default.svc"
    namespace: parchment
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/ParchmentMC/Atlas
      path: parchment-services
      targetRevision: HEAD
      helm:
        values: |-
          repository:
            url : https://github.com/ParchmentMC/Atlas
