apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 45.10.1
      helm:
        values: |-
          alertmanager:
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
                      selector: {}
          prometheus:
            prometheusSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi
                      selector: {}
          thanosRuler:
            thanosRulerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
                      selector: {}
          grafana:
            ingress:
              enabled: true
              ingressClassName: nginx
              hosts:
                - grafana.cluster.ldtteam.com
              annotations:
                kubernetes.io/ingress.class: nginx
                cert-manager.io/cluster-issuer: letsencrypt-production
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
    - repoURL: {{ .Values.repository.url }}
      path: charts/prometheus-extras
      targetRevision: HEAD
      helm:
        parameters:
          - name: domainName
            value: prometheus.cluster.ldtteam.com