apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 66.1.1
      helm:
        valuesObject:
          alertmanager:
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
          prometheus:
            prometheusSpec:
              podMonitorSelectorNilUsesHelmValues: false
              podMonitorSelector: { }
              podMonitorNamespaceSelector: { }
              serviceMonitorSelectorNilUsesHelmValues: false
              serviceMonitorSelector: { }
              serviceMonitorNamespaceSelector: { }
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 150Gi
          thanosRuler:
            thanosRulerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
          grafana:
            persistence:
              enabled: true
              size: 3Gi
            extraSecretMounts:
              - name: auth-github-secret-mount
                secretName: github-auth
                defaultMode: 0440
                mountPath: /etc/secrets/github-auth
                readOnly: true
            grafana.ini:
              server:
                domain: grafana.cluster.ldtteam.com
                root_url: https://grafana.cluster.ldtteam.com
              auth.github:
                client_id: Ov23liCjjnStcO8EzdfP
                client_secret: $__file{/etc/secrets/github-auth/client_secret}
                enabled: true
                allowed_organizations: ["ldtteam", "ParchmentMC", "ChiselsAndBits"]
                role_attribute_path: "contains(groups[*], '@ldtteam/cluster-admins') && 'GrafanaAdmin' || contains(groups[*], '@ParchmentMC/toolchain') && 'GrafanaAdmin' || contains(groups[*], '@ChiselsAndBits/cluster-admin') && 'GrafanaAdmin' || 'Viewer'"
              log:
                level: debug
            plugins:
              - grafana-simple-json-datasource
            ingress:
              enabled: true
              ingressClassName: nginx
              hosts:
                - grafana.cluster.ldtteam.com
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-production
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
                external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com"
              tls:
                - secretName: grafana-ingress-tls
                  hosts:
                    - grafana.cluster.ldtteam.com

    - repoURL: {{ .Values.repository.url }}
      path: core-charts/prometheus-extras
      targetRevision: HEAD
      helm:
        parameters:
          - name: domainName
            value: prometheus.cluster.ldtteam.com