apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: hub
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
          startupProbe: {{ $.Values.hub.startupProbe | toJson }}
          livenessProbe: {{ $.Values.hub.livenessProbe | toJson }}
          readinessProbe: {{ $.Values.hub.readinessProbe | toJson }}
          ports: {{ $.Values.hub.ports | toJson}}
          resources: {{ $.Values.hub.resources | toJson }}
          volumeMounts:
          {{- range $name, $volume := .Values.volumes }}
            - mountPath: {{ $volume.target }}
              name: {{ $name }}-hub
          {{-end}}
      volumes:
        {{- range $name, $volume := .Values.volumes }}
        - name: {{ $name }}-hub
          persistentVolumeClaim:
            claimName: {{ $name }}-hub
        {{-end}}
