apiVersion: batch/v1
kind: Job
metadata:
  name: backup-masterkey
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: backup-masterkey
        image: bitnami/kubectl:1.21
        command: ["/bin/sh", "-c"]
        workingDir: /scripts
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        args:
        - ./execute.sh
        volumeMounts:
          - name: scripts
            mountPath: /scripts/execute.sh
            subPath: execute.sh
          - name: scripts
            mountPath: /scripts/create-master-key-backup.sh
            subPath: create-master-key-backup.sh
          - name: scripts
            mountPath: /scripts/upload-to-bucket.sh
            subPath: upload-to-bucket.sh
        env:
          - name: S3_BUCKET
            value: "ldtteam-key-backup"
          - name: S3_HOST
            value: "s3.us-west-002.backblazeb2.com"
          - name: S3_KEY
            valueFrom:
              secretKeyRef:
                name: sealed-secrets-master-backups-data
                key: key-id
          - name: S3_SECRET
            valueFrom:
              secretKeyRef:
                name: sealed-secrets-master-backups-data
                key: application-key
      restartPolicy: OnFailure
      volumes:
        - name: scripts
          configMap:
            name: sealed-secrets-scripts
            defaultMode: 0777
  backoffLimit: 4
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 600