apiVersion: v1
kind: ConfigMap
metadata:
  name: sealed-secrets-scripts
  namespace: kube-system
data:
  upload-to-bucket.sh: |
    # Install backblaze b2
    curl -L 'https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux' -o 'b2' && chmod +x b2 && mv b2 /usr/local/bin/

    # We upload to backblaze b2
    b2 account authorize $S3_KEY $S3_SECRET

    # We upload the file to the bucket
    b2 upload-file $S3_BUCKET $1 $(basename $1)

  create-master-key-backup.sh: |
    #!/bin/bash

    # We need to export the secrets that hold the master key
    # to a file so that we can back it up to a secure location
    # and restore it if needed.

    mkdir -p /keys
    kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml > /keys/main.key
  execute.sh: |
    #!/bin/bash
    # export the master key
    ./create-master-key-backup.sh
    
    # upload the master key to a secure location
    ./upload-to-bucket.sh /keys/main.key
