{{- range .Values.bgp.remotes }}
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: {{ . }}
  namespace: {{ $.Values.namespace }}
spec:
  myASN: {{ $.Values.bgp.asn.mine }}
  peerASN: {{ $.Values.bgp.asn.external}}
  peerAddress: {{ . }}
  nodeSelectors:
    - matchLabels:
        ldtteam.com/ingress-host: {{ . }}
---
{{- end}}