apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipPool.name }}
  namespace: {{ .Values.namespace }}
spec:
  addresses:
    {{ .Values.ipPool.ranges | toYaml | indent 4}}