---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgBoOqeFFJHFbI7o70LfGyOVXe7KIkMQabevO3316vXz+yZSZ+yG4rM5on1yt3JbuaiyOGPOmgL5cxfrvQiA4FJZOtwtImgRwa6hFsKMt2pl84SlNxsS/lbGSNY1ufHQoTEJyeet6XhjcYwcV/ElSgzm/31KoGX8F/qQaTpuH1j9eWA0mA4ieQy7Se+IJQTvCXRtM70zp5gtgxpwOWj/sLMUIb5lFuHZNmGLZkhUcxD470bd2hHBi07LncVl1yn+n4AAlZ+4VZB9tKzej6LyALPjsMWYiRWiMC2f0iQ0bpFSMEaxkHepEp/z4VL6VbAdtGfM6ssAqy28hub/Frr48C0qxltKTYxHVRJHYm45HYt4tTzsxGi9FHnGFfK9KC47U/hKvwPA+R35sySLOla7eZQMcHBHPcAriLQ+PlCBS7+HqeeYGpTx9dsi4glMbNx4bhxHQkXko/MjIhml5F+8Zng7Rp9btyXxTmlC1Yq899BRHVUCnwuZYbDYBdAJlNnqTaG3KalUPX/iph/bKJZHZzZ6hNVIZrucRdAKOYdmydj4FWpG0d+GKAaY8cKiasax5wxL/EESvRq+ndHC0vkV0AFJH3Hrv+MK4q0eTngaO/NoJFi2edUmWCnpIskdffwcZ7PFGC+VcoVX87E7yjf7WhoSSSxKkyS8o7au/0HgQ6DsaJ9yVIf8v256RUxcURDFlTBAw2bIK4c543AnuV8AaPgWGCeiOPYrD/IUC839aDvtcA==
  template:
    metadata:
      name: hetzner-secret
      namespace: cert-manager
      labels:
        app.kubernetes.io/part-of: cert-manager
