---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgCHFmTPVwx6AmyUpr4jb1zVhaEz47gIUIr6sXRSZd2m7RGItlKsjIE85/2XG5zBHKKe9AQlM5QBXiOdQquJMEENVfubioXtThY97nZkguEQHsiN5TuCVfThaaIoccEu8qU7FZE3Bsw+3xp2sVRL50MUpzNS7fezoGFeydUiX0mLPs50XtBHnLLK1yUkmqurLw0nw/xBFo0EkAGE1kAYIMoiOmk0LgReFtSf5FFNwaYHM+5wWrVtTPDmZ3ypfSa2Bfl/t4w9L7WzacZu/1PeRDLhR9/j9OM9xjZWcRtpHEcx+NBOiFIJUZH/5YDEZAGvNMoZoh9959wHoMXiSmuIkNHRxHvN1LzYUVBtnzAfJYEB4OfFKyeP4pOVZm1Z6uH+LGwvg0NMuIa2zjGnOsnTnWex2dAvCVioyi/64B8rac9ht4xueNEOxYVm59U55qQ7Phyrf6V9MO4RjB74Et6lvJe/DbJiwirTQw/EzbnZe5+V2Y9dIjF/NWdewUk2Ai0qnACdh/UQSBMcCDX7+coyrgu8F8jL/BsThoJqCmgm+TLV650LKCuFxPKhmiMWunQgJGau8iLL/yA1BH6pYR0li7YVU5N054uEoO9d9Px6UjtMWKQGdWp9kpJMNqEm/QApxw3UqGYufjgZKF9T/Dg5n7aiBwxSAcobGk+Fwo9wMawvB2RFJZYjvH7d17bhV7l4drCnHr+pYlAOv0HyfJH1+WV2jMs33xKXZvq4vXHzUfAQTmcd6doaYMAJcP5raNE0ei9hglVOmvH5a7t64uDAdszc
  template:
    metadata:
      name: hetzner-secret
      namespace: cert-manager
      labels:
        app.kubernetes.io/part-of: cert-manager
