---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: parchmentmc-cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBktwhu4W3OBE2uUt4lprNqxaNCMkB7saWnqUBatCph7cMVdC46WIHH/nr9TV45KFbfC7L0P9vybUfIgpXPdnjhcOlVw46HMd1blBErY/YdleVDqjfL3nV80MHM++/OsI2xqzFeWogXn2EHUkd/mQ2X/SED4MByHjJa/UzrxAExtJ9GDVIJMJbBx2LXBfAIh006Tm+4hOkAiSPHwB2//HXOprBYAZ4ZqT14gIFRmIvn3+vUIk9irdrNzduYBxx54VXMGsJTLEQZPCKVMiCqf9KAq6lLOmpJ4guLdN5Si1MYRf0BzyPuFKwhq67Yn5ntfRQLXiMHRtlaWw9UhzoOJ0faqUyZPb+Fje+3+IaoItjLdsv54dDhBItu9rt24c1Vq9u2kslxe/5rHqX+P6vARjS4iYW5ErJ67ABgK3R7CG/ae4uGBITI9uCE0+E6ScL+VEYKNSfodhaI6KfijfdqeG4hfISlJb0csguWFCNtjFmgL6DFrqzPaqLp+KQD04eROasTrPa4OLe6QEouG8UHEI/Dr1weReAgnxXLNIya+nWdXWUlEgLL6mjfMTB1c21p2Pi9qB+bHMKCbvcln0YFjAVpn2ZvOJHR/gRLiAm8pbkmjN9BX8iJskN30byxRqgsYQU5yJ1nGp3GiXXGv9fLIsDUjxb2MNqpEelYqKpWbRj7Y2fUiDuT9L+MxKi7eqa/Wo+8DOymloomHypIF+nMyBGfFeeNne5zsv48DjGkflPA38NDWYBQbZQ5
  template:
    metadata:
      name: parchmentmc-cloudflare-api-token-secret
      namespace: cert-manager
      labels:
        app.kubernetes.io/part-of: cert-manager
