global:
  storageClass: longhorn

image:
  repository: jetbrains/hub
  pullPolicy: Always
  imagePullSecrets: []

replicas: 3

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    - auth.cluster.ldtteam.com

  tls:
    - secretName: teamcity-tls

## Teamcity deployed by StateFulSet
## @param teamcity.resources default value for all nodes in sts
hub:
  resources:
    requests:
      cpu: 100m
      memory: 2048Mi
  startupProbe: ~
  livenessProbe:
    httpGet:
      path: /healthCheck/healthy
      port: http
      scheme: HTTP
    failureThreshold: 3
    periodSeconds: 30
  readinessProbe:
    httpGet:
      path: /healthCheck/ready
      port: http
      scheme: HTTP
    failureThreshold: 2
    periodSeconds: 10
  ports:
  - containerPort: 8080
    name: http
    protocol: TCP
  affinity: {}
  tolerations: {}
  topologySpreadConstraints: {}

volumes:
  data:
    name: hub-data
    annotations:
      helm.sh/resource-policy: keep
    storageClassName: longhorn
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 20Gi

database:
  auth:
    username: hub
    password: hub
    database: hub
  architecture: replication