global:
  storageClass: longhorn

image:
  repository: jetbrains/hub
  pullPolicy: Always
  imagePullSecrets: []

replicas: 3

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    - auth.cluster.ldtteam.com

  tls:
    - secretName: teamcity-tls

## Teamcity deployed by StateFulSet
## @param teamcity.resources default value for all nodes in sts
hub:
  resources:
    requests:
      cpu: 100m
      memory: 2048Mi
  startupProbe:
    httpGet:
      path: /hub
      port: http
      scheme: HTTP
    failureThreshold: 30
    periodSeconds: 30
  livenessProbe:
    httpGet:
      path: /hub
      port: http
      scheme: HTTP
    failureThreshold: 3
    periodSeconds: 30
  readinessProbe:
    httpGet:
      path: /hub
      port: http
      scheme: HTTP
    failureThreshold: 10
    periodSeconds: 30
  ports:
  - containerPort: 8080
    name: http
    protocol: TCP
  affinity: {}
  tolerations: {}
  topologySpreadConstraints: {}

volumes:
  data:
    target: /opt/hub/data
    name: hub-data
    annotations:
      helm.sh/resource-policy: keep
    storageClassName: longhorn
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
  logs:
    target: /opt/hub/logs
    name: hub-logs
    annotations:
      helm.sh/resource-policy: keep
    storageClassName: longhorn
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
  backups:
    target: /opt/hub/backups
    name: hub-backups
    annotations:
      helm.sh/resource-policy: keep
    storageClassName: longhorn
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
  conf:
    target: /opt/hub/conf
    name: hub-conf
    annotations:
      helm.sh/resource-policy: keep
    storageClassName: longhorn
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 2Gi

database:
  auth:
    username: hub
    password: hub
    database: hub
  architecture: replication