apiVersion: v1
kind: Endpoints
metadata:
  name: rancher-management-backplane
  namespace: {{ .Release.Namespace }}
subsets:
  - addresses:
      - ip: 10.1.0.3
      - ip: 10.2.0.3
      - ip: 10.3.0.3
      - ip: 10.4.0.4
    ports:
      - port: 443
        protocol: TCP