apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-verify: "false"
    external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com"
spec:
  rules:
    - host: rancher.cluster.ldtteam.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rancher-management-backplane
                port:
                  number: 443
  tls:
    - hosts:
        - rancher.cluster.ldtteam.com
      secretName: rancher-tls