apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ldtteam-teamcity
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ldtteam-teamcity
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: {{ .Values.repository.url }}
      path: ldtteam-charts/teamcity
      targetRevision: HEAD
