apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ldtteam-weblate
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ldtteam-weblate
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: https://helm.weblate.org
      targetRevision: 0.4.31
      chart: weblate
      helm:
        values: |-
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              kubernetes.io/ingress.class: nginx
            hosts:
              - host: weblate.ldtteam.com
                paths: 
                  - path: "/"
                    pathType: "Prefix"
          adminEmail: marc.hermans+weblate@ldtteam.com
          emailHost: mail.ldtteam.com
          emailPort: 465
          existingSecret: weblate